import { createMiddleware } from 'hono/factory'
import type { FathomEnv } from '../cache'
import { paymentMiddlewareFromConfig } from '@x402/hono'
import { HTTPFacilitatorClient } from '@x402/core/server'
import { ExactEvmScheme } from '@x402/evm/exact/server'
import type { RoutesConfig } from '@x402/core/server'
import { declareDiscoveryExtension } from '@x402/extensions'
import { BUILDER_CODE, declareBuilderCodeExtension } from '@x402/extensions/builder-code'
import { parseX402Config } from '../utils/x402_config'
import {
  priceInputSchema, priceOutputSchema,
  pricesInputSchema, pricesOutputSchema,
  metadataInputSchema, metadataOutputSchema,
  metadatasInputSchema, metadatasOutputSchema,
  assessInputSchema, assessOutputSchema
} from '../schemas/x402DiscoverySchemas'

// Helper to fix the bazaar extension generated by the SDK
// The SDK nests output schema inside output.properties.example and forgets to make it required.
function createFixedDiscoveryExtension(config: any, outputSchema: any) {
  const ext = declareDiscoveryExtension(config) as any;
  if (ext.bazaar && ext.bazaar.schema && ext.bazaar.schema.properties) {
    // Overwrite the output schema with the real schema directly
    ext.bazaar.schema.properties.output = outputSchema;
    
    // Ensure both input and output are required
    ext.bazaar.schema.required = ["input", "output"];
    
    if (ext.bazaar.schema.properties.input?.properties?.method?.enum) {
        ext.bazaar.schema.properties.input.properties.method.enum = ["GET"];
    }
    if (ext.bazaar.info?.input) {
        ext.bazaar.info.input.method = "GET";
    }
    
    // To satisfy the SDK's internal AJV validation of `info.output` against `schema.properties.output`,
    // we must ensure `info.output` actually has the required fields defined in `outputSchema`.
    if (ext.bazaar.info?.output?.example) {
        const exampleData = ext.bazaar.info.output.example;
        // Merge the example data directly into info.output so it satisfies the schema requirements
        ext.bazaar.info.output = {
            ...exampleData,
            ...ext.bazaar.info.output // preserves "example" wrapper
        };
    }
  }
  return ext;
}

function createBuilderCodeExtension(env?: FathomEnv) {
  const builderCode = env?.BASE_BUILDER_CODE?.trim()
  if (!builderCode) {
    return {}
  }

  return {
    [BUILDER_CODE]: declareBuilderCodeExtension(builderCode)
  }
}

/**
 * Advertise the endpoint, not the request that happened to hit it.
 *
 * The Hono adapter builds `resource.url` from the full request URL, so an
 * unpaid GET for one token advertises
 * `/v1/price?token=0x9401...` as the resource - a different resource string for
 * every token anyone ever asks about. Of 500 resources in the CDP Bazaar index,
 * not one carries a query string; templated path segments appear, query
 * parameters never do. Fathom is absent from all 14,532 of them.
 *
 * The parameters are not lost: they are declared in the Bazaar extension's
 * `info.input.queryParams`, which is where a client is meant to read them from.
 * This only stops the resource identity from changing on every call.
 */
function stripQueryFromAdvertisedResource(res: Response): void {
  const header = res.headers.get('PAYMENT-REQUIRED') ?? res.headers.get('payment-required')
  if (!header) return

  try {
    const decoded = JSON.parse(atob(header))
    const url: unknown = decoded?.resource?.url
    if (typeof url !== 'string' || !url.includes('?')) return

    decoded.resource.url = url.split('?')[0]
    res.headers.set('PAYMENT-REQUIRED', btoa(JSON.stringify(decoded)))
  } catch (error) {
    // A challenge we cannot rewrite is still a valid challenge; leave it be.
    console.error('Could not normalise the advertised resource URL:', error)
  }
}

export const x402Middleware = createMiddleware<{ Bindings: FathomEnv }>(async (c, next) => {
  const authHeader = c.req.header('Authorization')
  if (authHeader && c.env?.ADMIN_AUTH_TOKEN && authHeader === `Bearer ${c.env.ADMIN_AUTH_TOKEN}`) {
    return next()
  }

  let x402Config;
  try {
    x402Config = parseX402Config(c.env)
  } catch (err: any) {
    console.error("X402_CONFIG_ERROR", err.message)
    return c.json({ error: 'config_error', message: 'Internal server config error' }, 500)
  }

  const builderCodeExtension = createBuilderCodeExtension(c.env)

  const baseAccepts = {
      scheme: "exact",
      network: x402Config.network as any,
      price: x402Config.price,
      payTo: x402Config.payTo
  }

  const batchAccepts = {
      ...baseAccepts,
      price: x402Config.batchPrice || x402Config.price
  }

  const routes: RoutesConfig = {
      "/v1/assess": {
          accepts: [baseAccepts],
          description: "Answer one question about a Base ERC-20: can I get out of this position, at this size, at a price I can trust? Quotes the exact sale you name on chain across five DEXes - Aerodrome, Aerodrome Slipstream, Uniswap V2/V3/V4 - and returns a single verdict to branch on: tradeable, caution, illiquid, or unverified. Pass size_usd for the position you actually hold; it is priced at that size rather than interpolated between standard quotes, because a guess about slippage is worse than no answer. The response separates what is measured about the token from what could not be established about it, so a failed reading is never mistaken for a bad token. Built for agents deciding whether to enter, exit, size, or value a long-tail position on Base.",
          mimeType: "application/json",
          tags: [
            "base", "exit-liquidity", "can-i-sell", "slippage", "price-impact",
            "execution", "pre-trade", "position-sizing", "risk", "long-tail",
            "token-risk", "trading-agent", "dex", "liquidity-check", "onchain-data"
          ],
          extensions: {
              ...builderCodeExtension,
              ...createFixedDiscoveryExtension({
                  input: { token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631", size_usd: 10000 },
                  inputSchema: assessInputSchema,
                  output: {
                      example: {
                          token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
                          chain: "base",
                          verdict: "tradeable",
                          reason: "$10,000 fills at 48 bps against a price corroborated across venues.",
                          size_usd: 10000,
                          exit: {
                              fillable: true,
                              proceeds_usd: 9951.96,
                              price_impact_bps: 48.04,
                              execution_price_usd: 0.4818
                          },
                          price_trust: {
                              confidence: 96,
                              measured_weight: 0.75,
                              sources: 6,
                              dispersion_bps: 39.7,
                              twap_deviation_bps: 0.85
                          }
                      }
                  }
              }, assessOutputSchema)
          }
      },
      "/v1/price": {
          accepts: [baseAccepts],
          description: "Decide whether a Base ERC-20 can be priced and exited before you trade it. Reads five DEXes on Base mainnet - Aerodrome, Aerodrome Slipstream, Uniswap V2/V3/V4 - and returns spot price cross-checked across independent pools, the pool's own TWAP against spot, and on-chain quotes for actually selling $1k, $5k and $10k with the price impact each costs. Built for long-tail tokens that major feeds either lack or quote without any sense of whether the market can absorb a sale. Every number is measured or absent: liquidity_usd is null for concentrated-liquidity pools rather than reporting L*sqrtP as a balance it is not, unmeasured components are excluded from the confidence score, and measured_weight says what share of the model that score rests on. Flags separate what is true about the token from what could not be established about it.",
          mimeType: "application/json",
          tags: [
            "base", "token-price", "long-tail", "dex", "liquidity", "exit-liquidity",
            "price-impact", "slippage", "execution", "sell-quote", "risk", "twap",
            "oracle", "trading-agent", "onchain-data", "erc20", "pre-trade"
          ],
          extensions: {
              ...builderCodeExtension,
              ...createFixedDiscoveryExtension({
                  input: { token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631" },
                  inputSchema: priceInputSchema,
                  output: { 
                      example: { 
                          token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
                          chain: "base",
                          status: "ok" 
                      }
                  }
              }, priceOutputSchema)
          }
      },
      "/v1/prices": {
          accepts: [batchAccepts],
          description: "Value or de-risk a whole Base portfolio in one paid call. Same measurement as /v1/price - spot cross-checked across five DEXes, TWAP against spot, executable $1k/$5k/$10k sell quotes with price impact, confidence and risk flags - for up to 50 Base ERC-20s at once. Use it to mark a book, screen a watchlist, or find which holdings cannot actually be exited at size. Each token reports its own status, so one unreadable token does not cost you the rest.",
          mimeType: "application/json",
          tags: [
            "base", "batch", "portfolio", "token-price", "long-tail", "liquidity",
            "exit-liquidity", "price-impact", "execution", "risk", "twap", "oracle",
            "trading-agent", "wallet", "onchain-data", "valuation"
          ],
          extensions: {
              ...builderCodeExtension,
              ...createFixedDiscoveryExtension({
                  input: { tokens: "0x940181a94A35A4569E4529A3CDfB74e38FD98631" },
                  inputSchema: pricesInputSchema,
                  output: { 
                      example: { 
                          chain: "base",
                          count: 1,
                          priced: 1,
                          failed: 0,
                          results: [{
                              token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631",
                              chain: "base",
                              status: "ok"
                          }]
                      }
                  }
              }, pricesOutputSchema)
          }
      },
      "/v1/metadata": {
          accepts: [baseAccepts],
          description: "Read a Base ERC-20's own identity from the chain: address, symbol, name and decimals, taken from the contract rather than from a list that can be stale or absent. Use it to resolve a token you have only an address for, before pricing it.",
          mimeType: "application/json",
          tags: ["base", "erc20", "metadata", "token", "decimals", "symbol", "onchain-data"],
          extensions: {
              ...builderCodeExtension,
              ...createFixedDiscoveryExtension({
                  input: { token: "0x940181a94A35A4569E4529A3CDfB74e38FD98631" },
                  inputSchema: metadataInputSchema,
                  output: { 
                      example: { 
                          address: "0x940181a94A35A4569E4529A3CDfB74e38FD98631", 
                          symbol: "AERO",
                          name: "Aerodrome",
                          decimals: 18
                      }
                  }
              }, metadataOutputSchema)
          }
      },
      "/v1/metadatas": {
          accepts: [batchAccepts],
          description: "Resolve many Base ERC-20s at once: address, symbol, name and decimals read from each contract. Use it to label a portfolio or a watchlist in one paid call before pricing it.",
          mimeType: "application/json",
          tags: ["base", "erc20", "metadata", "batch", "portfolio", "decimals", "symbol", "onchain-data"],
          extensions: {
              ...builderCodeExtension,
              ...createFixedDiscoveryExtension({
                  input: { tokens: "0x940181a94A35A4569E4529A3CDfB74e38FD98631" },
                  inputSchema: metadatasInputSchema,
                  output: { 
                      example: { 
                          chain: "base",
                          count: 1,
                          results: [{
                              address: "0x940181a94A35A4569E4529A3CDfB74e38FD98631", 
                              symbol: "AERO",
                              name: "Aerodrome",
                              decimals: 18
                          }]
                      }
                  }
              }, metadatasOutputSchema)
          }
      },
      "*": {
          accepts: [baseAccepts],
          extensions: builderCodeExtension
      }
  }

  try {
    const middleware = paymentMiddlewareFromConfig(
      routes,
      [new HTTPFacilitatorClient({ 
        url: x402Config.facilitatorUrl,
        createAuthHeaders: x402Config.createAuthHeaders
      })],
      [{ network: x402Config.network as any, server: new ExactEvmScheme() }]
    )

    const res = await middleware(c, next)
    if (res && res.status === 402) {
      res.headers.set('Cache-Control', 'no-store, no-cache, must-revalidate')
      stripQueryFromAdvertisedResource(res)
    }
    return res
  } catch (err) {
    console.error("X402_MIDDLEWARE_ERROR", err)
    throw err
  }
})
